
// vulkan_vtable.cpp

#include "header.h"

struct VkGeneratedDispatchTableCore tableVk;

int InitVulkan()
{
  if(tableVk.GetInstanceProcAddr)
    return 1;

  tableVk.libVulkan = dlopen("libvulkan.so", RTLD_NOW | RTLD_LOCAL);
  if( !tableVk.libVulkan)
    return 0;

  tableVk.GetInstanceProcAddr = reinterpret_cast<PFN_vkGetInstanceProcAddr>(dlsym(tableVk.libVulkan, "vkGetInstanceProcAddr") );

  tableVk.AcquireNextImageKHR = reinterpret_cast<PFN_vkAcquireNextImageKHR>(dlsym(tableVk.libVulkan, "vkAcquireNextImageKHR") );
  tableVk.AllocateCommandBuffers = reinterpret_cast<PFN_vkAllocateCommandBuffers>(dlsym(tableVk.libVulkan, "vkAllocateCommandBuffers") );
  tableVk.AllocateDescriptorSets = reinterpret_cast<PFN_vkAllocateDescriptorSets>(dlsym(tableVk.libVulkan, "vkAllocateDescriptorSets") );
  tableVk.AllocateMemory = reinterpret_cast<PFN_vkAllocateMemory>(dlsym(tableVk.libVulkan, "vkAllocateMemory") );
  tableVk.BeginCommandBuffer = reinterpret_cast<PFN_vkBeginCommandBuffer>(dlsym(tableVk.libVulkan, "vkBeginCommandBuffer") );
  tableVk.BindBufferMemory = reinterpret_cast<PFN_vkBindBufferMemory>(dlsym(tableVk.libVulkan, "vkBindBufferMemory") );
  tableVk.BindImageMemory = reinterpret_cast<PFN_vkBindImageMemory>(dlsym(tableVk.libVulkan, "vkBindImageMemory") );
  tableVk.CmdBeginQuery = reinterpret_cast<PFN_vkCmdBeginQuery>(dlsym(tableVk.libVulkan, "vkCmdBeginQuery") );
  tableVk.CmdBeginRenderPass = reinterpret_cast<PFN_vkCmdBeginRenderPass>(dlsym(tableVk.libVulkan, "vkCmdBeginRenderPass") );
  tableVk.CmdBindDescriptorSets = reinterpret_cast<PFN_vkCmdBindDescriptorSets>(dlsym(tableVk.libVulkan, "vkCmdBindDescriptorSets") );
  tableVk.CmdBindIndexBuffer = reinterpret_cast<PFN_vkCmdBindIndexBuffer>(dlsym(tableVk.libVulkan, "vkCmdBindIndexBuffer") );
  tableVk.CmdBindPipeline = reinterpret_cast<PFN_vkCmdBindPipeline>(dlsym(tableVk.libVulkan, "vkCmdBindPipeline") );
  tableVk.CmdBindVertexBuffers = reinterpret_cast<PFN_vkCmdBindVertexBuffers>(dlsym(tableVk.libVulkan, "vkCmdBindVertexBuffers") );
  tableVk.CmdBlitImage = reinterpret_cast<PFN_vkCmdBlitImage>(dlsym(tableVk.libVulkan, "vkCmdBlitImage") );
  tableVk.CmdClearAttachments = reinterpret_cast<PFN_vkCmdClearAttachments>(dlsym(tableVk.libVulkan, "vkCmdClearAttachments") );
  tableVk.CmdClearColorImage = reinterpret_cast<PFN_vkCmdClearColorImage>(dlsym(tableVk.libVulkan, "vkCmdClearColorImage") );
  tableVk.CmdClearDepthStencilImage = reinterpret_cast<PFN_vkCmdClearDepthStencilImage>(dlsym(tableVk.libVulkan, "vkCmdClearDepthStencilImage") );
  tableVk.CmdCopyBuffer = reinterpret_cast<PFN_vkCmdCopyBuffer>(dlsym(tableVk.libVulkan, "vkCmdCopyBuffer") );
  tableVk.CmdCopyBufferToImage = reinterpret_cast<PFN_vkCmdCopyBufferToImage>(dlsym(tableVk.libVulkan, "vkCmdCopyBufferToImage") );
  tableVk.CmdCopyImage = reinterpret_cast<PFN_vkCmdCopyImage>(dlsym(tableVk.libVulkan, "vkCmdCopyImage") );
  tableVk.CmdCopyImageToBuffer = reinterpret_cast<PFN_vkCmdCopyImageToBuffer>(dlsym(tableVk.libVulkan, "vkCmdCopyImageToBuffer") );
  tableVk.CmdCopyQueryPoolResults = reinterpret_cast<PFN_vkCmdCopyQueryPoolResults>(dlsym(tableVk.libVulkan, "vkCmdCopyQueryPoolResults") );
  tableVk.CmdDispatch = reinterpret_cast<PFN_vkCmdDispatch>(dlsym(tableVk.libVulkan, "vkCmdDispatch") );
  tableVk.CmdDispatchIndirect = reinterpret_cast<PFN_vkCmdDispatchIndirect>(dlsym(tableVk.libVulkan, "vkCmdDispatchIndirect") );
  tableVk.CmdDraw = reinterpret_cast<PFN_vkCmdDraw>(dlsym(tableVk.libVulkan, "vkCmdDraw") );
  tableVk.CmdDrawIndexed = reinterpret_cast<PFN_vkCmdDrawIndexed>(dlsym(tableVk.libVulkan, "vkCmdDrawIndexed") );
  tableVk.CmdDrawIndexedIndirect = reinterpret_cast<PFN_vkCmdDrawIndexedIndirect>(dlsym(tableVk.libVulkan, "vkCmdDrawIndexedIndirect") );
  tableVk.CmdDrawIndirect = reinterpret_cast<PFN_vkCmdDrawIndirect>(dlsym(tableVk.libVulkan, "vkCmdDrawIndirect") );
  tableVk.CmdEndQuery = reinterpret_cast<PFN_vkCmdEndQuery>(dlsym(tableVk.libVulkan, "vkCmdEndQuery") );
  tableVk.CmdEndRenderPass = reinterpret_cast<PFN_vkCmdEndRenderPass>(dlsym(tableVk.libVulkan, "vkCmdEndRenderPass") );
  tableVk.CmdExecuteCommands = reinterpret_cast<PFN_vkCmdExecuteCommands>(dlsym(tableVk.libVulkan, "vkCmdExecuteCommands") );
  tableVk.CmdFillBuffer = reinterpret_cast<PFN_vkCmdFillBuffer>(dlsym(tableVk.libVulkan, "vkCmdFillBuffer") );
  tableVk.CmdNextSubpass = reinterpret_cast<PFN_vkCmdNextSubpass>(dlsym(tableVk.libVulkan, "vkCmdNextSubpass") );
  tableVk.CmdPipelineBarrier = reinterpret_cast<PFN_vkCmdPipelineBarrier>(dlsym(tableVk.libVulkan, "vkCmdPipelineBarrier") );
  tableVk.CmdPushConstants = reinterpret_cast<PFN_vkCmdPushConstants>(dlsym(tableVk.libVulkan, "vkCmdPushConstants") );
  tableVk.CmdResetEvent = reinterpret_cast<PFN_vkCmdResetEvent>(dlsym(tableVk.libVulkan, "vkCmdResetEvent") );
  tableVk.CmdResetQueryPool = reinterpret_cast<PFN_vkCmdResetQueryPool>(dlsym(tableVk.libVulkan, "vkCmdResetQueryPool") );
  tableVk.CmdResolveImage = reinterpret_cast<PFN_vkCmdResolveImage>(dlsym(tableVk.libVulkan, "vkCmdResolveImage") );
  tableVk.CmdSetBlendConstants = reinterpret_cast<PFN_vkCmdSetBlendConstants>(dlsym(tableVk.libVulkan, "vkCmdSetBlendConstants") );
  tableVk.CmdSetDepthBias = reinterpret_cast<PFN_vkCmdSetDepthBias>(dlsym(tableVk.libVulkan, "vkCmdSetDepthBias") );
  tableVk.CmdSetDepthBounds = reinterpret_cast<PFN_vkCmdSetDepthBounds>(dlsym(tableVk.libVulkan, "vkCmdSetDepthBounds") );
  tableVk.CmdSetEvent = reinterpret_cast<PFN_vkCmdSetEvent>(dlsym(tableVk.libVulkan, "vkCmdSetEvent") );
  tableVk.CmdSetLineWidth = reinterpret_cast<PFN_vkCmdSetLineWidth>(dlsym(tableVk.libVulkan, "vkCmdSetLineWidth") );
  tableVk.CmdSetScissor = reinterpret_cast<PFN_vkCmdSetScissor>(dlsym(tableVk.libVulkan, "vkCmdSetScissor") );
  tableVk.CmdSetStencilCompareMask = reinterpret_cast<PFN_vkCmdSetStencilCompareMask>(dlsym(tableVk.libVulkan, "vkCmdSetStencilCompareMask") );
  tableVk.CmdSetStencilReference = reinterpret_cast<PFN_vkCmdSetStencilReference>(dlsym(tableVk.libVulkan, "vkCmdSetStencilReference") );
  tableVk.CmdSetStencilWriteMask = reinterpret_cast<PFN_vkCmdSetStencilWriteMask>(dlsym(tableVk.libVulkan, "vkCmdSetStencilWriteMask") );
  tableVk.CmdSetViewport = reinterpret_cast<PFN_vkCmdSetViewport>(dlsym(tableVk.libVulkan, "vkCmdSetViewport") );
  tableVk.CmdUpdateBuffer = reinterpret_cast<PFN_vkCmdUpdateBuffer>(dlsym(tableVk.libVulkan, "vkCmdUpdateBuffer") );
  tableVk.CmdWaitEvents = reinterpret_cast<PFN_vkCmdWaitEvents>(dlsym(tableVk.libVulkan, "vkCmdWaitEvents") );
  tableVk.CmdWriteTimestamp = reinterpret_cast<PFN_vkCmdWriteTimestamp>(dlsym(tableVk.libVulkan, "vkCmdWriteTimestamp") );
  tableVk.CreateAndroidSurfaceKHR = reinterpret_cast<PFN_vkCreateAndroidSurfaceKHR>(dlsym(tableVk.libVulkan, "vkCreateAndroidSurfaceKHR") );
  tableVk.CreateBuffer = reinterpret_cast<PFN_vkCreateBuffer>(dlsym(tableVk.libVulkan, "vkCreateBuffer") );
  tableVk.CreateBufferView = reinterpret_cast<PFN_vkCreateBufferView>(dlsym(tableVk.libVulkan, "vkCreateBufferView") );
  tableVk.CreateCommandPool = reinterpret_cast<PFN_vkCreateCommandPool>(dlsym(tableVk.libVulkan, "vkCreateCommandPool") );
  tableVk.CreateComputePipelines = reinterpret_cast<PFN_vkCreateComputePipelines>(dlsym(tableVk.libVulkan, "vkCreateComputePipelines") );
  tableVk.CreateDescriptorPool = reinterpret_cast<PFN_vkCreateDescriptorPool>(dlsym(tableVk.libVulkan, "vkCreateDescriptorPool") );
  tableVk.CreateDescriptorSetLayout = reinterpret_cast<PFN_vkCreateDescriptorSetLayout>(dlsym(tableVk.libVulkan, "vkCreateDescriptorSetLayout") );
  tableVk.CreateDevice = reinterpret_cast<PFN_vkCreateDevice>(dlsym(tableVk.libVulkan, "vkCreateDevice") );
  tableVk.CreateEvent = reinterpret_cast<PFN_vkCreateEvent>(dlsym(tableVk.libVulkan, "vkCreateEvent") );
  tableVk.CreateFence = reinterpret_cast<PFN_vkCreateFence>(dlsym(tableVk.libVulkan, "vkCreateFence") );
  tableVk.CreateFramebuffer = reinterpret_cast<PFN_vkCreateFramebuffer>(dlsym(tableVk.libVulkan, "vkCreateFramebuffer") );
  tableVk.CreateGraphicsPipelines = reinterpret_cast<PFN_vkCreateGraphicsPipelines>(dlsym(tableVk.libVulkan, "vkCreateGraphicsPipelines") );
  tableVk.CreateImage = reinterpret_cast<PFN_vkCreateImage>(dlsym(tableVk.libVulkan, "vkCreateImage") );
  tableVk.CreateImageView = reinterpret_cast<PFN_vkCreateImageView>(dlsym(tableVk.libVulkan, "vkCreateImageView") );
  tableVk.CreateInstance = reinterpret_cast<PFN_vkCreateInstance>(dlsym(tableVk.libVulkan, "vkCreateInstance") );
  tableVk.CreatePipelineCache = reinterpret_cast<PFN_vkCreatePipelineCache>(dlsym(tableVk.libVulkan, "vkCreatePipelineCache") );
  tableVk.CreatePipelineLayout = reinterpret_cast<PFN_vkCreatePipelineLayout>(dlsym(tableVk.libVulkan, "vkCreatePipelineLayout") );
  tableVk.CreateQueryPool = reinterpret_cast<PFN_vkCreateQueryPool>(dlsym(tableVk.libVulkan, "vkCreateQueryPool") );
  tableVk.CreateRenderPass = reinterpret_cast<PFN_vkCreateRenderPass>(dlsym(tableVk.libVulkan, "vkCreateRenderPass") );
  tableVk.CreateSampler = reinterpret_cast<PFN_vkCreateSampler>(dlsym(tableVk.libVulkan, "vkCreateSampler") );
  tableVk.CreateSemaphore = reinterpret_cast<PFN_vkCreateSemaphore>(dlsym(tableVk.libVulkan, "vkCreateSemaphore") );
  tableVk.CreateShaderModule = reinterpret_cast<PFN_vkCreateShaderModule>(dlsym(tableVk.libVulkan, "vkCreateShaderModule") );
  tableVk.CreateSwapchainKHR = reinterpret_cast<PFN_vkCreateSwapchainKHR>(dlsym(tableVk.libVulkan, "vkCreateSwapchainKHR") );
  tableVk.DestroyBuffer = reinterpret_cast<PFN_vkDestroyBuffer>(dlsym(tableVk.libVulkan, "vkDestroyBuffer") );
  tableVk.DestroyBufferView = reinterpret_cast<PFN_vkDestroyBufferView>(dlsym(tableVk.libVulkan, "vkDestroyBufferView") );
  tableVk.DestroyCommandPool = reinterpret_cast<PFN_vkDestroyCommandPool>(dlsym(tableVk.libVulkan, "vkDestroyCommandPool") );
  tableVk.DestroyDescriptorPool = reinterpret_cast<PFN_vkDestroyDescriptorPool>(dlsym(tableVk.libVulkan, "vkDestroyDescriptorPool") );
  tableVk.DestroyDescriptorSetLayout = reinterpret_cast<PFN_vkDestroyDescriptorSetLayout>(dlsym(tableVk.libVulkan, "vkDestroyDescriptorSetLayout") );
  tableVk.DestroyDevice = reinterpret_cast<PFN_vkDestroyDevice>(dlsym(tableVk.libVulkan, "vkDestroyDevice") );
  tableVk.DestroyEvent = reinterpret_cast<PFN_vkDestroyEvent>(dlsym(tableVk.libVulkan, "vkDestroyEvent") );
  tableVk.DestroyFence = reinterpret_cast<PFN_vkDestroyFence>(dlsym(tableVk.libVulkan, "vkDestroyFence") );
  tableVk.DestroyFramebuffer = reinterpret_cast<PFN_vkDestroyFramebuffer>(dlsym(tableVk.libVulkan, "vkDestroyFramebuffer") );
  tableVk.DestroyImage = reinterpret_cast<PFN_vkDestroyImage>(dlsym(tableVk.libVulkan, "vkDestroyImage") );
  tableVk.DestroyImageView = reinterpret_cast<PFN_vkDestroyImageView>(dlsym(tableVk.libVulkan, "vkDestroyImageView") );
  tableVk.DestroyInstance = reinterpret_cast<PFN_vkDestroyInstance>(dlsym(tableVk.libVulkan, "vkDestroyInstance") );
  tableVk.DestroyPipeline = reinterpret_cast<PFN_vkDestroyPipeline>(dlsym(tableVk.libVulkan, "vkDestroyPipeline") );
  tableVk.DestroyPipelineCache = reinterpret_cast<PFN_vkDestroyPipelineCache>(dlsym(tableVk.libVulkan, "vkDestroyPipelineCache") );
  tableVk.DestroyPipelineLayout = reinterpret_cast<PFN_vkDestroyPipelineLayout>(dlsym(tableVk.libVulkan, "vkDestroyPipelineLayout") );
  tableVk.DestroyQueryPool = reinterpret_cast<PFN_vkDestroyQueryPool>(dlsym(tableVk.libVulkan, "vkDestroyQueryPool") );
  tableVk.DestroyRenderPass = reinterpret_cast<PFN_vkDestroyRenderPass>(dlsym(tableVk.libVulkan, "vkDestroyRenderPass") );
  tableVk.DestroySampler = reinterpret_cast<PFN_vkDestroySampler>(dlsym(tableVk.libVulkan, "vkDestroySampler") );
  tableVk.DestroySemaphore = reinterpret_cast<PFN_vkDestroySemaphore>(dlsym(tableVk.libVulkan, "vkDestroySemaphore") );
  tableVk.DestroyShaderModule = reinterpret_cast<PFN_vkDestroyShaderModule>(dlsym(tableVk.libVulkan, "vkDestroyShaderModule") );
  tableVk.DestroySurfaceKHR = reinterpret_cast<PFN_vkDestroySurfaceKHR>(dlsym(tableVk.libVulkan, "vkDestroySurfaceKHR") );
  tableVk.DestroySwapchainKHR = reinterpret_cast<PFN_vkDestroySwapchainKHR>(dlsym(tableVk.libVulkan, "vkDestroySwapchainKHR") );
  tableVk.DeviceWaitIdle = reinterpret_cast<PFN_vkDeviceWaitIdle>(dlsym(tableVk.libVulkan, "vkDeviceWaitIdle") );
  tableVk.EndCommandBuffer = reinterpret_cast<PFN_vkEndCommandBuffer>(dlsym(tableVk.libVulkan, "vkEndCommandBuffer") );
  tableVk.EnumerateDeviceExtensionProperties = reinterpret_cast<PFN_vkEnumerateDeviceExtensionProperties>(dlsym(tableVk.libVulkan, "vkEnumerateDeviceExtensionProperties") );
  tableVk.EnumerateDeviceLayerProperties = reinterpret_cast<PFN_vkEnumerateDeviceLayerProperties>(dlsym(tableVk.libVulkan, "vkEnumerateDeviceLayerProperties") );
  tableVk.EnumerateInstanceExtensionProperties = reinterpret_cast<PFN_vkEnumerateInstanceExtensionProperties>(dlsym(tableVk.libVulkan, "vkEnumerateInstanceExtensionProperties") );
  tableVk.EnumerateInstanceLayerProperties = reinterpret_cast<PFN_vkEnumerateInstanceLayerProperties>(dlsym(tableVk.libVulkan, "vkEnumerateInstanceLayerProperties") );
  tableVk.EnumeratePhysicalDevices = reinterpret_cast<PFN_vkEnumeratePhysicalDevices>(dlsym(tableVk.libVulkan, "vkEnumeratePhysicalDevices") );
  tableVk.FlushMappedMemoryRanges = reinterpret_cast<PFN_vkFlushMappedMemoryRanges>(dlsym(tableVk.libVulkan, "vkFlushMappedMemoryRanges") );
  tableVk.FreeCommandBuffers = reinterpret_cast<PFN_vkFreeCommandBuffers>(dlsym(tableVk.libVulkan, "vkFreeCommandBuffers") );
  tableVk.FreeDescriptorSets = reinterpret_cast<PFN_vkFreeDescriptorSets>(dlsym(tableVk.libVulkan, "vkFreeDescriptorSets") );
  tableVk.FreeMemory = reinterpret_cast<PFN_vkFreeMemory>(dlsym(tableVk.libVulkan, "vkFreeMemory") );
  tableVk.GetBufferMemoryRequirements = reinterpret_cast<PFN_vkGetBufferMemoryRequirements>(dlsym(tableVk.libVulkan, "vkGetBufferMemoryRequirements") );
  tableVk.GetDeviceMemoryCommitment = reinterpret_cast<PFN_vkGetDeviceMemoryCommitment>(dlsym(tableVk.libVulkan, "vkGetDeviceMemoryCommitment") );
  tableVk.GetDeviceProcAddr = reinterpret_cast<PFN_vkGetDeviceProcAddr>(dlsym(tableVk.libVulkan, "vkGetDeviceProcAddr") );
  tableVk.GetDeviceQueue = reinterpret_cast<PFN_vkGetDeviceQueue>(dlsym(tableVk.libVulkan, "vkGetDeviceQueue") );
  tableVk.GetEventStatus = reinterpret_cast<PFN_vkGetEventStatus>(dlsym(tableVk.libVulkan, "vkGetEventStatus") );
  tableVk.GetFenceStatus = reinterpret_cast<PFN_vkGetFenceStatus>(dlsym(tableVk.libVulkan, "vkGetFenceStatus") );
  tableVk.GetImageMemoryRequirements = reinterpret_cast<PFN_vkGetImageMemoryRequirements>(dlsym(tableVk.libVulkan, "vkGetImageMemoryRequirements") );
  tableVk.GetImageSparseMemoryRequirements = reinterpret_cast<PFN_vkGetImageSparseMemoryRequirements>(dlsym(tableVk.libVulkan, "vkGetImageSparseMemoryRequirements") );
  tableVk.GetImageSubresourceLayout = reinterpret_cast<PFN_vkGetImageSubresourceLayout>(dlsym(tableVk.libVulkan, "vkGetImageSubresourceLayout") );

  tableVk.GetPhysicalDeviceFeatures = reinterpret_cast<PFN_vkGetPhysicalDeviceFeatures>(dlsym(tableVk.libVulkan, "vkGetPhysicalDeviceFeatures") );
  tableVk.GetPhysicalDeviceFormatProperties = reinterpret_cast<PFN_vkGetPhysicalDeviceFormatProperties>(dlsym(tableVk.libVulkan, "vkGetPhysicalDeviceFormatProperties") );
  tableVk.GetPhysicalDeviceImageFormatProperties = reinterpret_cast<PFN_vkGetPhysicalDeviceImageFormatProperties>(dlsym(tableVk.libVulkan, "vkGetPhysicalDeviceImageFormatProperties") );
  tableVk.GetPhysicalDeviceMemoryProperties = reinterpret_cast<PFN_vkGetPhysicalDeviceMemoryProperties>(dlsym(tableVk.libVulkan, "vkGetPhysicalDeviceMemoryProperties") );
  tableVk.GetPhysicalDeviceProperties = reinterpret_cast<PFN_vkGetPhysicalDeviceProperties>(dlsym(tableVk.libVulkan, "vkGetPhysicalDeviceProperties") );
  tableVk.GetPhysicalDeviceQueueFamilyProperties = reinterpret_cast<PFN_vkGetPhysicalDeviceQueueFamilyProperties>(dlsym(tableVk.libVulkan, "vkGetPhysicalDeviceQueueFamilyProperties") );
  tableVk.GetPhysicalDeviceSparseImageFormatProperties = reinterpret_cast<PFN_vkGetPhysicalDeviceSparseImageFormatProperties>(dlsym(tableVk.libVulkan, "vkGetPhysicalDeviceSparseImageFormatProperties") );
  tableVk.GetPhysicalDeviceSurfaceCapabilitiesKHR = reinterpret_cast<PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR>(dlsym(tableVk.libVulkan, "vkGetPhysicalDeviceSurfaceCapabilitiesKHR") );
  tableVk.GetPhysicalDeviceSurfaceFormatsKHR = reinterpret_cast<PFN_vkGetPhysicalDeviceSurfaceFormatsKHR>(dlsym(tableVk.libVulkan, "vkGetPhysicalDeviceSurfaceFormatsKHR") );
  tableVk.GetPhysicalDeviceSurfacePresentModesKHR = reinterpret_cast<PFN_vkGetPhysicalDeviceSurfacePresentModesKHR>(dlsym(tableVk.libVulkan, "vkGetPhysicalDeviceSurfacePresentModesKHR") );
  tableVk.GetPhysicalDeviceSurfaceSupportKHR = reinterpret_cast<PFN_vkGetPhysicalDeviceSurfaceSupportKHR>(dlsym(tableVk.libVulkan, "vkGetPhysicalDeviceSurfaceSupportKHR") );
  tableVk.GetPipelineCacheData = reinterpret_cast<PFN_vkGetPipelineCacheData>(dlsym(tableVk.libVulkan, "vkGetPipelineCacheData") );
  tableVk.GetQueryPoolResults = reinterpret_cast<PFN_vkGetQueryPoolResults>(dlsym(tableVk.libVulkan, "vkGetQueryPoolResults") );
  tableVk.GetRenderAreaGranularity = reinterpret_cast<PFN_vkGetRenderAreaGranularity>(dlsym(tableVk.libVulkan, "vkGetRenderAreaGranularity") );
  tableVk.GetSwapchainImagesKHR = reinterpret_cast<PFN_vkGetSwapchainImagesKHR>(dlsym(tableVk.libVulkan, "vkGetSwapchainImagesKHR") );
  tableVk.InvalidateMappedMemoryRanges = reinterpret_cast<PFN_vkInvalidateMappedMemoryRanges>(dlsym(tableVk.libVulkan, "vkInvalidateMappedMemoryRanges") );
  tableVk.MapMemory = reinterpret_cast<PFN_vkMapMemory>(dlsym(tableVk.libVulkan, "vkMapMemory") );
  tableVk.MergePipelineCaches = reinterpret_cast<PFN_vkMergePipelineCaches>(dlsym(tableVk.libVulkan, "vkMergePipelineCaches") );
  tableVk.QueueBindSparse = reinterpret_cast<PFN_vkQueueBindSparse>(dlsym(tableVk.libVulkan, "vkQueueBindSparse") );
  tableVk.QueuePresentKHR = reinterpret_cast<PFN_vkQueuePresentKHR>(dlsym(tableVk.libVulkan, "vkQueuePresentKHR") );
  tableVk.QueueSubmit = reinterpret_cast<PFN_vkQueueSubmit>(dlsym(tableVk.libVulkan, "vkQueueSubmit") );
  tableVk.QueueWaitIdle = reinterpret_cast<PFN_vkQueueWaitIdle>(dlsym(tableVk.libVulkan, "vkQueueWaitIdle") );
  tableVk.ResetCommandBuffer = reinterpret_cast<PFN_vkResetCommandBuffer>(dlsym(tableVk.libVulkan, "vkResetCommandBuffer") );
  tableVk.ResetCommandPool = reinterpret_cast<PFN_vkResetCommandPool>(dlsym(tableVk.libVulkan, "vkResetCommandPool") );
  tableVk.ResetDescriptorPool = reinterpret_cast<PFN_vkResetDescriptorPool>(dlsym(tableVk.libVulkan, "vkResetDescriptorPool") );
  tableVk.ResetEvent = reinterpret_cast<PFN_vkResetEvent>(dlsym(tableVk.libVulkan, "vkResetEvent") );
  tableVk.ResetFences = reinterpret_cast<PFN_vkResetFences>(dlsym(tableVk.libVulkan, "vkResetFences") );
  tableVk.SetEvent = reinterpret_cast<PFN_vkSetEvent>(dlsym(tableVk.libVulkan, "vkSetEvent") );
  tableVk.UnmapMemory = reinterpret_cast<PFN_vkUnmapMemory>(dlsym(tableVk.libVulkan, "vkUnmapMemory") );
  tableVk.UpdateDescriptorSets = reinterpret_cast<PFN_vkUpdateDescriptorSets>(dlsym(tableVk.libVulkan, "vkUpdateDescriptorSets") );
  tableVk.WaitForFences = reinterpret_cast<PFN_vkWaitForFences>(dlsym(tableVk.libVulkan, "vkWaitForFences") );

  tableVk.CreateDisplayModeKHR = reinterpret_cast<PFN_vkCreateDisplayModeKHR>(dlsym(tableVk.libVulkan, "vkCreateDisplayModeKHR") );
  tableVk.CreateDisplayPlaneSurfaceKHR = reinterpret_cast<PFN_vkCreateDisplayPlaneSurfaceKHR>(dlsym(tableVk.libVulkan, "vkCreateDisplayPlaneSurfaceKHR") );
  tableVk.CreateSharedSwapchainsKHR = reinterpret_cast<PFN_vkCreateSharedSwapchainsKHR>(dlsym(tableVk.libVulkan, "vkCreateSharedSwapchainsKHR") );
  tableVk.GetDisplayModePropertiesKHR = reinterpret_cast<PFN_vkGetDisplayModePropertiesKHR>(dlsym(tableVk.libVulkan, "vkGetDisplayModePropertiesKHR") );
  tableVk.GetDisplayPlaneCapabilitiesKHR = reinterpret_cast<PFN_vkGetDisplayPlaneCapabilitiesKHR>(dlsym(tableVk.libVulkan, "vkGetDisplayPlaneCapabilitiesKHR") );
  tableVk.GetDisplayPlaneSupportedDisplaysKHR = reinterpret_cast<PFN_vkGetDisplayPlaneSupportedDisplaysKHR>(dlsym(tableVk.libVulkan, "vkGetDisplayPlaneSupportedDisplaysKHR") );
  tableVk.GetPhysicalDeviceDisplayPlanePropertiesKHR = reinterpret_cast<PFN_vkGetPhysicalDeviceDisplayPlanePropertiesKHR>(dlsym(tableVk.libVulkan, "vkGetPhysicalDeviceDisplayPlanePropertiesKHR") );
  tableVk.GetPhysicalDeviceDisplayPropertiesKHR = reinterpret_cast<PFN_vkGetPhysicalDeviceDisplayPropertiesKHR>(dlsym(tableVk.libVulkan, "vkGetPhysicalDeviceDisplayPropertiesKHR") );

  tableVk.AcquireNextImage2KHR = reinterpret_cast<PFN_vkAcquireNextImage2KHR>(dlsym(tableVk.libVulkan, "vkAcquireNextImage2KHR") );
  tableVk.BindBufferMemory2 = reinterpret_cast<PFN_vkBindBufferMemory2>(dlsym(tableVk.libVulkan, "vkBindBufferMemory2") );
  tableVk.BindImageMemory2 = reinterpret_cast<PFN_vkBindImageMemory2>(dlsym(tableVk.libVulkan, "vkBindImageMemory2") );
  tableVk.CmdBeginRenderPass2 = reinterpret_cast<PFN_vkCmdBeginRenderPass2>(dlsym(tableVk.libVulkan, "vkCmdBeginRenderPass2") );
  tableVk.CmdDispatchBase = reinterpret_cast<PFN_vkCmdDispatchBase>(dlsym(tableVk.libVulkan, "vkCmdDispatchBase") );
  tableVk.CmdDrawIndexedIndirectCount = reinterpret_cast<PFN_vkCmdDrawIndexedIndirectCount>(dlsym(tableVk.libVulkan, "vkCmdDrawIndexedIndirectCount") );
  tableVk.CmdDrawIndirectCount = reinterpret_cast<PFN_vkCmdDrawIndirectCount>(dlsym(tableVk.libVulkan, "vkCmdDrawIndirectCount") );
  tableVk.CmdEndRenderPass2 = reinterpret_cast<PFN_vkCmdEndRenderPass2>(dlsym(tableVk.libVulkan, "vkCmdEndRenderPass2") );
  tableVk.CmdNextSubpass2 = reinterpret_cast<PFN_vkCmdNextSubpass2>(dlsym(tableVk.libVulkan, "vkCmdNextSubpass2") );
  tableVk.CmdSetDeviceMask = reinterpret_cast<PFN_vkCmdSetDeviceMask>(dlsym(tableVk.libVulkan, "vkCmdSetDeviceMask") );
  tableVk.CreateDescriptorUpdateTemplate = reinterpret_cast<PFN_vkCreateDescriptorUpdateTemplate>(dlsym(tableVk.libVulkan, "vkCreateDescriptorUpdateTemplate") );
  tableVk.CreateRenderPass2 = reinterpret_cast<PFN_vkCreateRenderPass2>(dlsym(tableVk.libVulkan, "vkCreateRenderPass2") );
  tableVk.CreateSamplerYcbcrConversion = reinterpret_cast<PFN_vkCreateSamplerYcbcrConversion>(dlsym(tableVk.libVulkan, "vkCreateSamplerYcbcrConversion") );
  tableVk.DestroyDescriptorUpdateTemplate = reinterpret_cast<PFN_vkDestroyDescriptorUpdateTemplate>(dlsym(tableVk.libVulkan, "vkDestroyDescriptorUpdateTemplate") );
  tableVk.DestroySamplerYcbcrConversion = reinterpret_cast<PFN_vkDestroySamplerYcbcrConversion>(dlsym(tableVk.libVulkan, "vkDestroySamplerYcbcrConversion") );
  tableVk.EnumerateInstanceVersion = reinterpret_cast<PFN_vkEnumerateInstanceVersion>(dlsym(tableVk.libVulkan, "vkEnumerateInstanceVersion") );
  tableVk.EnumeratePhysicalDeviceGroups = reinterpret_cast<PFN_vkEnumeratePhysicalDeviceGroups>(dlsym(tableVk.libVulkan, "vkEnumeratePhysicalDeviceGroups") );
  tableVk.GetAndroidHardwareBufferPropertiesANDROID = reinterpret_cast<PFN_vkGetAndroidHardwareBufferPropertiesANDROID>(dlsym(tableVk.libVulkan, "vkGetAndroidHardwareBufferPropertiesANDROID") );
  tableVk.GetBufferDeviceAddress = reinterpret_cast<PFN_vkGetBufferDeviceAddress>(dlsym(tableVk.libVulkan, "vkGetBufferDeviceAddress") );
  tableVk.GetBufferMemoryRequirements2 = reinterpret_cast<PFN_vkGetBufferMemoryRequirements2>(dlsym(tableVk.libVulkan, "vkGetBufferMemoryRequirements2") );
  tableVk.GetBufferOpaqueCaptureAddress = reinterpret_cast<PFN_vkGetBufferOpaqueCaptureAddress>(dlsym(tableVk.libVulkan, "vkGetBufferOpaqueCaptureAddress") );
  tableVk.GetDescriptorSetLayoutSupport = reinterpret_cast<PFN_vkGetDescriptorSetLayoutSupport>(dlsym(tableVk.libVulkan, "vkGetDescriptorSetLayoutSupport") );
  tableVk.GetDeviceGroupPeerMemoryFeatures = reinterpret_cast<PFN_vkGetDeviceGroupPeerMemoryFeatures>(dlsym(tableVk.libVulkan, "vkGetDeviceGroupPeerMemoryFeatures") );
  tableVk.GetDeviceGroupPresentCapabilitiesKHR = reinterpret_cast<PFN_vkGetDeviceGroupPresentCapabilitiesKHR>(dlsym(tableVk.libVulkan, "vkGetDeviceGroupPresentCapabilitiesKHR") );
  tableVk.GetDeviceGroupSurfacePresentModesKHR = reinterpret_cast<PFN_vkGetDeviceGroupSurfacePresentModesKHR>(dlsym(tableVk.libVulkan, "vkGetDeviceGroupSurfacePresentModesKHR") );
  tableVk.GetDeviceMemoryOpaqueCaptureAddress = reinterpret_cast<PFN_vkGetDeviceMemoryOpaqueCaptureAddress>(dlsym(tableVk.libVulkan, "vkGetDeviceMemoryOpaqueCaptureAddress") );
  tableVk.GetDeviceQueue2 = reinterpret_cast<PFN_vkGetDeviceQueue2>(dlsym(tableVk.libVulkan, "vkGetDeviceQueue2") );
  tableVk.GetImageMemoryRequirements2 = reinterpret_cast<PFN_vkGetImageMemoryRequirements2>(dlsym(tableVk.libVulkan, "vkGetImageMemoryRequirements2") );
  tableVk.GetImageSparseMemoryRequirements2 = reinterpret_cast<PFN_vkGetImageSparseMemoryRequirements2>(dlsym(tableVk.libVulkan, "vkGetImageSparseMemoryRequirements2") );
  tableVk.GetMemoryAndroidHardwareBufferANDROID = reinterpret_cast<PFN_vkGetMemoryAndroidHardwareBufferANDROID>(dlsym(tableVk.libVulkan, "vkGetMemoryAndroidHardwareBufferANDROID") );
  tableVk.GetPhysicalDeviceExternalBufferProperties = reinterpret_cast<PFN_vkGetPhysicalDeviceExternalBufferProperties>(dlsym(tableVk.libVulkan, "vkGetPhysicalDeviceExternalBufferProperties") );
  tableVk.GetPhysicalDeviceExternalFenceProperties = reinterpret_cast<PFN_vkGetPhysicalDeviceExternalFenceProperties>(dlsym(tableVk.libVulkan, "vkGetPhysicalDeviceExternalFenceProperties") );
  tableVk.GetPhysicalDeviceExternalSemaphoreProperties = reinterpret_cast<PFN_vkGetPhysicalDeviceExternalSemaphoreProperties>(dlsym(tableVk.libVulkan, "vkGetPhysicalDeviceExternalSemaphoreProperties") );
  tableVk.GetPhysicalDeviceFeatures2 = reinterpret_cast<PFN_vkGetPhysicalDeviceFeatures2>(dlsym(tableVk.libVulkan, "vkGetPhysicalDeviceFeatures2") );
  tableVk.GetPhysicalDeviceFormatProperties2 = reinterpret_cast<PFN_vkGetPhysicalDeviceFormatProperties2>(dlsym(tableVk.libVulkan, "vkGetPhysicalDeviceFormatProperties2") );
  tableVk.GetPhysicalDeviceImageFormatProperties2 = reinterpret_cast<PFN_vkGetPhysicalDeviceImageFormatProperties2>(dlsym(tableVk.libVulkan, "vkGetPhysicalDeviceImageFormatProperties2") );
  tableVk.GetPhysicalDeviceMemoryProperties2 = reinterpret_cast<PFN_vkGetPhysicalDeviceMemoryProperties2>(dlsym(tableVk.libVulkan, "vkGetPhysicalDeviceMemoryProperties2") );
  tableVk.GetPhysicalDevicePresentRectanglesKHR = reinterpret_cast<PFN_vkGetPhysicalDevicePresentRectanglesKHR>(dlsym(tableVk.libVulkan, "vkGetPhysicalDevicePresentRectanglesKHR") );
  tableVk.GetPhysicalDeviceProperties2 = reinterpret_cast<PFN_vkGetPhysicalDeviceProperties2>(dlsym(tableVk.libVulkan, "vkGetPhysicalDeviceProperties2") );
  tableVk.GetPhysicalDeviceQueueFamilyProperties2 = reinterpret_cast<PFN_vkGetPhysicalDeviceQueueFamilyProperties2>(dlsym(tableVk.libVulkan, "vkGetPhysicalDeviceQueueFamilyProperties2") );
  tableVk.GetPhysicalDeviceSparseImageFormatProperties2 = reinterpret_cast<PFN_vkGetPhysicalDeviceSparseImageFormatProperties2>(dlsym(tableVk.libVulkan, "vkGetPhysicalDeviceSparseImageFormatProperties2") );
  tableVk.GetSemaphoreCounterValue = reinterpret_cast<PFN_vkGetSemaphoreCounterValue>(dlsym(tableVk.libVulkan, "vkGetSemaphoreCounterValue") );
  tableVk.ResetQueryPool = reinterpret_cast<PFN_vkResetQueryPool>(dlsym(tableVk.libVulkan, "vkResetQueryPool") );
  tableVk.SignalSemaphore = reinterpret_cast<PFN_vkSignalSemaphore>(dlsym(tableVk.libVulkan, "vkSignalSemaphore") );
  tableVk.TrimCommandPool = reinterpret_cast<PFN_vkTrimCommandPool>(dlsym(tableVk.libVulkan, "vkTrimCommandPool") );
  tableVk.UpdateDescriptorSetWithTemplate = reinterpret_cast<PFN_vkUpdateDescriptorSetWithTemplate>(dlsym(tableVk.libVulkan, "vkUpdateDescriptorSetWithTemplate") );
  tableVk.WaitSemaphores = reinterpret_cast<PFN_vkWaitSemaphores>(dlsym(tableVk.libVulkan, "vkWaitSemaphores") );

  // VK_EXT_debug_marker
  tableVk.CmdDebugMarkerBeginEXT = reinterpret_cast<PFN_vkCmdDebugMarkerBeginEXT>(dlsym(tableVk.libVulkan, "vkCmdDebugMarkerBeginEXT") );
  tableVk.CmdDebugMarkerEndEXT = reinterpret_cast<PFN_vkCmdDebugMarkerEndEXT>(dlsym(tableVk.libVulkan, "vkCmdDebugMarkerEndEXT") );
  tableVk.CmdDebugMarkerInsertEXT = reinterpret_cast<PFN_vkCmdDebugMarkerInsertEXT>(dlsym(tableVk.libVulkan, "vkCmdDebugMarkerInsertEXT") );
  tableVk.DebugMarkerSetObjectNameEXT = reinterpret_cast<PFN_vkDebugMarkerSetObjectNameEXT>(dlsym(tableVk.libVulkan, "vkDebugMarkerSetObjectNameEXT") );
  tableVk.DebugMarkerSetObjectTagEXT = reinterpret_cast<PFN_vkDebugMarkerSetObjectTagEXT>(dlsym(tableVk.libVulkan, "vkDebugMarkerSetObjectTagEXT") );

  // VK_EXT_debug_report
  tableVk.CreateDebugReportCallbackEXT = reinterpret_cast<PFN_vkCreateDebugReportCallbackEXT>(dlsym(tableVk.libVulkan, "vkCreateDebugReportCallbackEXT") );
  tableVk.DebugReportMessageEXT = reinterpret_cast<PFN_vkDebugReportMessageEXT>(dlsym(tableVk.libVulkan, "vkDebugReportMessageEXT") );
  tableVk.DestroyDebugReportCallbackEXT = reinterpret_cast<PFN_vkDestroyDebugReportCallbackEXT>(dlsym(tableVk.libVulkan, "vkDestroyDebugReportCallbackEXT") );

  // VK_EXT_debug_utils
  tableVk.CmdBeginDebugUtilsLabelEXT = reinterpret_cast<PFN_vkCmdBeginDebugUtilsLabelEXT>(dlsym(tableVk.libVulkan, "vkCmdBeginDebugUtilsLabelEXT") );
  tableVk.CmdEndDebugUtilsLabelEXT = reinterpret_cast<PFN_vkCmdEndDebugUtilsLabelEXT>(dlsym(tableVk.libVulkan, "vkCmdEndDebugUtilsLabelEXT") );
  tableVk.CmdInsertDebugUtilsLabelEXT = reinterpret_cast<PFN_vkCmdInsertDebugUtilsLabelEXT>(dlsym(tableVk.libVulkan, "vkCmdInsertDebugUtilsLabelEXT") );
  tableVk.CreateDebugUtilsMessengerEXT = reinterpret_cast<PFN_vkCreateDebugUtilsMessengerEXT>(dlsym(tableVk.libVulkan, "vkCreateDebugUtilsMessengerEXT") );
  tableVk.DestroyDebugUtilsMessengerEXT = reinterpret_cast<PFN_vkDestroyDebugUtilsMessengerEXT>(dlsym(tableVk.libVulkan, "vkDestroyDebugUtilsMessengerEXT") );
  tableVk.QueueBeginDebugUtilsLabelEXT = reinterpret_cast<PFN_vkQueueBeginDebugUtilsLabelEXT>(dlsym(tableVk.libVulkan, "vkQueueBeginDebugUtilsLabelEXT") );
  tableVk.QueueEndDebugUtilsLabelEXT = reinterpret_cast<PFN_vkQueueEndDebugUtilsLabelEXT>(dlsym(tableVk.libVulkan, "vkQueueEndDebugUtilsLabelEXT") );
  tableVk.QueueInsertDebugUtilsLabelEXT = reinterpret_cast<PFN_vkQueueInsertDebugUtilsLabelEXT>(dlsym(tableVk.libVulkan, "vkQueueInsertDebugUtilsLabelEXT") );
  tableVk.SetDebugUtilsObjectNameEXT = reinterpret_cast<PFN_vkSetDebugUtilsObjectNameEXT>(dlsym(tableVk.libVulkan, "vkSetDebugUtilsObjectNameEXT") );
  tableVk.SetDebugUtilsObjectTagEXT = reinterpret_cast<PFN_vkSetDebugUtilsObjectTagEXT>(dlsym(tableVk.libVulkan, "vkSetDebugUtilsObjectTagEXT") );
  tableVk.SubmitDebugUtilsMessageEXT = reinterpret_cast<PFN_vkSubmitDebugUtilsMessageEXT>(dlsym(tableVk.libVulkan, "vkSubmitDebugUtilsMessageEXT") );

  return 1;
}
